version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    container_name: nginx
  node:
    build:
      context: .
      target: development
    # container_name: node-app
    volumes:
      - ./:/app:ro
      - /app/node_modules
    depends_on:
      - mongo
      - redis
    deploy:
      replicas: 2
    env_file:
      - .env
    command: npm run dev

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo-db:
