version: '3.8'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
