version: '3.8'
services:
  node:
    build:
      context: .
      target: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    depends_on:
      - mongo
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: npm run dev

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
